import uuid
import logging
from typing import List, Optional
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.models.extracted_document import ExtractedDocument
from app.models.syllabus_topic import SyllabusTopic
from app.services.structured_output import StructuredOutputService

logger = logging.getLogger(__name__)


class SyllabusTopicSchema(BaseModel):
    topic_name: str = Field(description="Actionable title of the academic topic (e.g. 'Binary Trees')")
    unit_title: str = Field(description="Name of the course unit this topic belongs to (e.g. 'Unit 2: Trees')")
    importance_score: float = Field(description="Importance score indicating weight from 0.0 to 10.0")
    estimated_hours: float = Field(description="Estimated master study hours (e.g. 3.5)")
    difficulty_level: str = Field(description="Complexity level of this topic. Must be: 'easy', 'medium', or 'hard'")
    dependencies: List[str] = Field(description="Prerequisite topic names in the syllabus required to master this first")
    priority_rank: int = Field(description="Chronological learning order sequence rank (1-indexed)")


class SyllabusAnalysisSchema(BaseModel):
    course_name: str = Field(description="Overall name of the academic course")
    subject_code: str = Field(description="Official academic code (e.g. 'CS101')")
    estimated_difficulty: str = Field(description="General course difficulty. Must be: 'easy', 'medium', or 'hard'")
    topics: List[SyllabusTopicSchema] = Field(description="List of all syllabus topics grouped chronologically")


class SyllabusAnalyzerService:

    @staticmethod
    def analyze_syllabus(db: Session, file_id: str) -> dict:
        """
        Parses document text, calls the structured LLM to build a course map,
        and saves topics to PostgreSQL.
        """
        try:
            fid = uuid.UUID(file_id)
        except ValueError:
            raise ValueError("Invalid file_id format. Must be a valid UUID.")

        extracted_doc = db.query(ExtractedDocument).filter(ExtractedDocument.file_id == fid).first()
        if not extracted_doc:
            raise ValueError(f"Extracted document metadata for file_id {file_id} not found in database.")

        prompt = f"""
        You are an expert academic syllabus and course outline analyzer.
        Your task is to analyze the following course text and extract a structured hierarchical course map.

        Ensure that:
        1. Every topic has a clear topic_name and belongs to a specific parent unit_title.
        2. Assign a logical importance_score from 0.0 (low) to 10.0 (high) indicating exam weight.
        3. Estimate masters study hours (estimated_hours) needed for a student to study this topic.
        4. Validate that difficulty_level is strictly one of: 'easy', 'medium', 'hard'.
        5. Map prerequisite topics from this document into the 'dependencies' array.
        6. Compute a sequential priority_rank indicating the master sequence.

        Syllabus Text:
        {extracted_doc.extracted_text[:12000]}
        """

        logger.info(f"Running structured syllabus analyzer for doc ID: {extracted_doc.id}")
        
        extracted_data = StructuredOutputService.generate_structured(
            response_model=SyllabusAnalysisSchema,
            prompt=prompt,
            max_retries=3
        )

        # Clear existing syllabus topics for this document to prevent duplicates on refresh
        db.query(SyllabusTopic).filter(SyllabusTopic.document_id == extracted_doc.id).delete()

        # Insert topics
        db_topics = []
        for topic_data in extracted_data.topics:
            db_topic = SyllabusTopic(
                document_id=extracted_doc.id,
                topic_name=topic_data.topic_name,
                unit_title=topic_data.unit_title,
                importance_score=topic_data.importance_score,
                estimated_hours=topic_data.estimated_hours,
                difficulty_level=topic_data.difficulty_level.lower(),
                priority_rank=topic_data.priority_rank,
                dependencies=",".join(topic_data.dependencies) if topic_data.dependencies else ""
            )
            db.add(db_topic)
            db_topics.append(db_topic)

        # Update parent document metadata status
        extracted_doc.syllabus_detected = True
        extracted_doc.estimated_difficulty = extracted_data.estimated_difficulty.lower()
        extracted_doc.total_topics = len(extracted_data.topics)
        
        db.commit()
        
        # Force refresh to populate autogenerated columns
        db.refresh(extracted_doc)
        for t in db_topics:
            db.refresh(t)

        return {
            "file_id": str(fid),
            "course_name": extracted_data.course_name,
            "subject_code": extracted_data.subject_code,
            "estimated_difficulty": extracted_doc.estimated_difficulty,
            "total_topics": extracted_doc.total_topics,
            "topics": [
                {
                    "id": t.id,
                    "topic_name": t.topic_name,
                    "unit_title": t.unit_title,
                    "importance_score": t.importance_score,
                    "estimated_hours": t.estimated_hours,
                    "difficulty_level": t.difficulty_level,
                    "priority_rank": t.priority_rank,
                    "dependencies": t.dependencies.split(",") if t.dependencies else []
                }
                for t in db_topics
            ]
        }
